<a href="https://colab.research.google.com/github/unique91/Numpy-Refresher/blob/main/Numpy_Refresher1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Datatypes in python are objects with lots of properties and methods
a = 3
print(len(dir(a)))
dir(a)[-10:]

In [4]:
# NumPy stands for numerical python and provides a richt collection of operations for numerical data types
# Points array
pt = [[0, 1], [10, 5], [7, 3]]

# Random points
from random import randint
num_pt = 5
x_range = (0, 20)
y_range = (0, 30)
pt = [[randint(*x_range), randint(*y_range)] for _ in range(num_pt)]


In [5]:
# Convert python list to a numpy ndarray
import numpy as np
pt = np.array(pt)

In [6]:
# Random points by using numpy library
x_range = (0, 10)
y_range = (0, 50)
pt = np.random.randint(low=(x_range[0], y_range[0]), high=(x_range[1], y_range[1]), size=(10, 2))

In [7]:
# Performance
# 1 Python
%timeit \
pt = [[randint(*x_range), randint(*y_range)] for _ in range(100000)]

209 ms ± 57.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
# 2. NumPy
%timeit \
pt = np.random.randint(low=(x_range[0], y_range[0]), high=(x_range[1], y_range[1]), size=(100000, 2))

6.47 ms ± 98 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# Converting Lists to Arrays
py_list = [1, 2, 3, 4, 5, 6]
np_array = np.array(py_list)
# print(py_list)
# np_array

py_list2 =  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
np_array2 = np.array(py_list2)
# print(py_list2)
print(np_array2 , '\n')

# Slicing and Indexing
print('First row:\t\t\t{}\n'.format(np_array2[0]))
print('First row:\t\t\t{}\n'.format(np_array2[0, :]))
print('First column:\t\t\t{}\n'.format(np_array2[:, 0]))
print('3rd row 2nd column element:\t{}\n'.format(np_array2[2, 1]))
print('Last 2 rows and last 2 columns\n{}\n'.format(np_array2[-2:, -2:]))
print('Array with 1st and 3rd col:\n{}\n'.format(np_array2[:, [0, 2]]))

# Basic attributes of Numpy arrays
def array_info(arr):
  print("Array:\n{}".format(arr))
  print("Data type:\t{}".format(arr.dtype))
  print("Array shape:\t{}".format(arr.shape))

In [ ]:
from numpy.core.numeric import array_equal
# Creating NumPy arrays using built-in functions and datatypes

# Sequence array
arr = np.arange(10, dtype=np.int64)
array_info(arr)

# linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
linespace = np.linspace(0, 10, 3, dtype=np.float32)  # 3 elements between 0-10
array_info(linespace)

# Zero array/matrix
zeros = np.zeros((2, 3), dtype=np.float32)
array_info(zeros)

# Ones Array
ones = np.ones((3, 2), dtype=np.int8)
array_info(ones)

# Identity array/matrix
identity = np.eye(5, dtype=np.float32)
array_info(identity)

# Constat array/matrix
const_arr = np.full((3, 3), 9.81)
array_info(const_arr)

# Random integers array/matrix
rand_int = np.random.randint(5, 10, (2, 3))  # 2x3, values lies in [5, 10]
array_info(rand_int)

# Random array
random_array = np.random.random((4, 4))
array_info(random_array)

# Boolean array
bool_array = random_array > 0.5
array_info(bool_array)

In [ ]:
# Data Types conversion
age_in_years = np.random.randint(0, 100, 10)
# Convert to uint8
age_in_years = age_in_years.astype(np.uint8)
array_info(age_in_years)
# Convert to float64
age_in_years = age_in_years.astype(np.float64)
array_info(age_in_years)

In [ ]:
# Mathematical Functions
# 1. Exponential function
array = np.array([np.full(3, -1), np.zeros(3), np.ones(3)], dtype=np.uint8)
array_info(array)
exp_array = np.exp(array)
array_info(exp_array)
# 2. Square root
array = np.arange(5)
root_array = np.sqrt(array)
array_info(root_array)
# 3. Power
array = np.arange(0, 6, dtype=np.int64)
pow_array = np.power(array, 3)
array_info(pow_array)
# 4. Logarithm
array = np.array([0, np.exp(1), np.exp(1)**2, 1, 10])
array_info(array)
log_array = np.log(array)
array_info(log_array)

In [24]:
# Clip Values
array = np.random.random((3, 3))
array_info(array)
array_clip = np.clip(array, 0.3, 0.5)
array_info(array_clip)

Array:
[[0.06230372 0.79517042 0.32228202]
 [0.70914692 0.26007581 0.16877271]
 [0.42960581 0.18088012 0.01896973]]
Data type:	float64
Array shape:	(3, 3)
Array:
[[0.3        0.5        0.32228202]
 [0.5        0.3        0.3       ]
 [0.42960581 0.3        0.3       ]]
Data type:	float64
Array shape:	(3, 3)
