<a href="https://colab.research.google.com/github/unique91/Numpy-Refresher/blob/main/Numpy_Refresher2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def array_info(array):
  print('Array:\n{}'.format(array))
  print('Data type:\t{}'.format(array.dtype))
  print('Array shape:\t{}'.format(array.shape))
  print('Array Dim:\t{}\n'.format(array.ndim))

# Reshape (important concept for machine learning and computer vision!)
# Reshaping an array changes the shape of the data without altering the data itself. Reshaping arrays requires that the number of data elements remains constant.

# 1D array
arr = np.arange(1, 10, dtype=int)
array_info(arr)
print("arr[3] = ", arr[3])

# Reshape the 1D array to a (1x10) 2D array.
arr = arr.reshape(1, 9)  # same(1, -1)
array_info(arr)
print("arr[0] = ", arr[0])
print("arr[0, 3] = ", arr[0, 3])

# We can reshape the arry into any shape that are factor of 9 (1x9), (3x3), (9x1)

# Reshaping Multi-Demensional Arrays
arrN = np.array([
    [[10, 11], [10, 12], [10, 13], [10, 14], [10, 15]],
    [[20, 21], [20, 22], [20, 23], [20, 24], [20, 25]],
    [[30, 31], [30, 32], [30, 33], [30, 34], [30, 35]],
])
array_info(arrN)
print("arrN[0,0,:] = ", arrN[0,0,:])
arrN = arrN.reshape(3, 10)
array_info(arrN)

In [ ]:
from numpy.core.multiarray import array
# Adding an Axis / Dimension
arr = np.arange(1, 10, dtype=int)
arr = arr.reshape(3, 3)
array_info(arr)

# Add a new axis to the (3x3) array to create a 3D array -> (1x3x3)
arrN = arr.reshape(1, 3, 3)
array_info(arrN)

# Expand Dimensions
# reshape or expand_dims or np.newaxis do the same thing
arr2 = np.arange(1, 10, dtype=int)
# Reshape to (3x3)
arr2 = arr2.reshape(3, 3)
array_info(arr2)
# Expand dimensions
arr3 = np.expand_dims(arr2, axis=0)
array_info(arr3)
# Expand dimensions with newaxis
arr4 = arr2[np.newaxis, :, :]
array_info(arr4)

# Squeeze (Remove redundant axis)
arr = np.arange(1, 10, dtype=int)
arr = arr.reshape(1, 3, 3)
array_info(arr)
arr_squeezed = np.squeeze(arr, axis=0)
array_info(arr_squeezed)

# Reshape Revisit
arr5 = np.arange(10)
arr5 = arr5.reshape(-1, 2) # two columns
array_info(arr5)
arr6 = arr5.copy()
arr6 = arr6.reshape(2, -1) # two rows
array_info(arr6)

In [ ]:
# Flattening Arrays
# Create three separate (4x4) arrays
h1 = np.full((4, 4), 1, dtype='float32')
h2 = np.full((4, 4), 2, dtype='float32')
h3 = np.full((4, 4), 3, dtype='float32')

# Create a (3x4x4) array
h = np.zeros((3, 4, 4))
h[0] = h1
h[1] = h2
h[2] = h3
array_info(h)

h = h.reshape(1, 3, 16)
array_info(h)

In [27]:
# Combining Arrays / Matrices

# 1. Method (Concatenate)
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])
arr_concat = np.concatenate((arr, arr2), axis=0)
array_info(arr_concat)

# Horizontal/Vertical Stack
arr3 = np.array([[1, 1, 1], [2, 2, 2]])
arr4 = np.array([[3, 3, 3], [4, 4, 4]])

h_stack = np.hstack((arr3, arr4))
v_stack = np.vstack((arr3, arr4))

print("Horizontal stack:")
array_info(h_stack)
print("Vertical stack:")
array_info(v_stack)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2

Horizontal stack: 
Array:
[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]
Data type:	int64
Array shape:	(2, 6)
Array Dim:	2

Vertical stack: 
Array:
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
Data type:	int64
Array shape:	(4, 3)
Array Dim:	2

